services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: scheduler-app-prod
    ports:
      - "8080:8080"
    # Use individual environment variables that are read by config.go
    environment:
      - POSTGRES_HOST=postgresql # Use the service name as the host
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_ADDR=redis:6379 # Gunakan nama service sebagai host
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TZ=${TZ:-UTC}
    depends_on:
      - postgresql
      - redis

  postgresql:
    image: postgres:13-alpine
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ:-UTC}
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data-prod:/var/lib/postgresql/data
    # In a real production setup, you might not expose the DB port publicly
    # ports:
    #   - "5432:5432"

  redis:
    image: redis:6-alpine
    environment:
      - TZ=${TZ:-UTC}
    # You also might not expose the Redis port publicly
    # ports:
    #   - "6379:6379"

  asynqmon:
    image: hibiken/asynqmon:latest
    container_name: scheduler-asynqmon-prod
    # Port 8081 is for example only. In production, it should ideally be accessed via a reverse proxy.
    ports:
      - "8081:8081"
    command: --redis-addr=redis:6379
    depends_on:
      - redis

volumes:
  postgres-data-prod: