services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: scheduler-app-dev
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - REDIS_URL=${REDIS_ADDR}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - TZ=${TZ:-UTC}
    depends_on:
      - postgresql
      - redis

  postgresql:
    image: postgres:13-alpine
    container_name: scheduler-postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ:-UTC}
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]  # Updated healthcheck
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: scheduler-redis
    command: redis-server --appendonly yes --appendfsync everysec
    environment:
      - TZ=${TZ:-UTC}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  redis-data: