package main

import (
	"context"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"

	_ "github.com/rizqitaufiqf/go-scheduler/docs" // docs is generated by Swag CLI

	"github.com/rizqitaufiqf/go-scheduler/config"
	"github.com/rizqitaufiqf/go-scheduler/database"
	scheduler "github.com/rizqitaufiqf/go-scheduler/repository"
	"github.com/rizqitaufiqf/go-scheduler/router"
	worker "github.com/rizqitaufiqf/go-scheduler/worker"
)

// @title Go Task Scheduler API
// @version 1.0
// @description An API for scheduling and managing product-related tasks.
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email support@swagger.io
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host      localhost:8080
// @BasePath  /api/v1
// @schemes http

func main() {
	// Load Configuration
	cfg, err := config.LoadConfig()
	if err != nil {
		log.Fatalf("Could not load config: %v", err)
	}

	// Initialize Database (PostgreSQL)
	gormDB, err := database.InitDB(cfg.DBSource)
	if err != nil {
		log.Fatalf("Could not connect to the database: %v", err)
	}
	log.Println("Database connected and migrations are done.")

	// Initialize Redis
	redisClient := database.InitRedis(cfg.RedisURL)
	if _, err := redisClient.Ping(redisClient.Context()).Result(); err != nil {
		log.Fatalf("Could not connect to Redis: %v", err)
	}
	log.Println("Redis connected.")

	// Initialize Scheduler and Worker
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// Initialize core components scheduler first
	appScheduler := scheduler.NewScheduler(ctx, gormDB, redisClient)

	// Initialize Notification Publisher (Redis Streams)
	notificationPublisher := worker.NewNotificationPublisher(redisClient)

	// Initialize Router
	router, notificationRepo, sseManager := router.SetupRouter(gormDB, appScheduler)

	// Initialize Notification Consumer (Redis Streams)
	notificationConsumer := worker.NewNotificationConsumer(
		redisClient,
		notificationRepo,
		sseManager,
	)

	// Start the background worker in a goroutine
	appWorker := worker.NewWorker(ctx, gormDB, redisClient, notificationPublisher, cfg)
	// Start Task Worker
	go func() {
		log.Println("🔨 Starting task worker...")
		appWorker.Start(ctx)
	}()

	// Start Notification Consumer (Redis Streams)
	go func() {
		log.Println("📥 Starting notification consumer...")
		if err := notificationConsumer.Start(ctx); err != nil {
			log.Fatalf("❌ Failed to start notification consumer: %v", err)
		}
	}()

	// Periodic cleanup of old messages from Redis Stream
	go func() {
		ticker := time.NewTicker(1 * time.Hour)
		defer ticker.Stop()

		for {
			select {
			case <-ctx.Done():
				return
			case <-ticker.C:
				log.Println("🧹 Running periodic cleanup...")
				if err := notificationConsumer.CleanupOldMessages(ctx); err != nil {
					log.Printf("⚠️  Failed to cleanup old messages: %v", err)
				}
			}
		}
	}()

	go func() {
		if err := router.Run(":8080"); err != nil {
			log.Fatalf("Failed to run server: %v", err)
		}
	}()
	log.Println("🚀 Starting server on :8080")

	// Wait for interrupt signal for graceful shutdown
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	log.Println("🛑 Shutting down gracefully...")
	cancel() // Cancel context to stop all goroutines

	// Give some time for graceful shutdown
	time.Sleep(2 * time.Second)

	log.Println("✅ Server stopped successfully")
}
