package main

import (
	"context"
	"log"

	_ "github.com/rizqitaufiqf/go-scheduler/docs" // docs is generated by Swag CLI

	"github.com/rizqitaufiqf/go-scheduler/config"
	"github.com/rizqitaufiqf/go-scheduler/database"
	scheduler "github.com/rizqitaufiqf/go-scheduler/repository"
	"github.com/rizqitaufiqf/go-scheduler/router"
	worker "github.com/rizqitaufiqf/go-scheduler/worker"
)

// @title Go Task Scheduler API
// @version 1.0
// @description An API for scheduling and managing product-related tasks.
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email support@swagger.io
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host      localhost:8080
// @BasePath  /api/v1
// @schemes http

func main() {
	// 1. Load Configuration
	cfg, err := config.LoadConfig()
	if err != nil {
		log.Fatalf("Could not load config: %v", err)
	}

	// 2. Initialize Database (PostgreSQL)
	gormDB, err := database.InitDB(cfg.DBSource)
	if err != nil {
		log.Fatalf("Could not connect to the database: %v", err)
	}
	log.Println("Database connected and migrations are done.")

	// 3. Initialize Redis
	redisClient := database.InitRedis(cfg.RedisURL)
	if _, err := redisClient.Ping(redisClient.Context()).Result(); err != nil {
		log.Fatalf("Could not connect to Redis: %v", err)
	}
	log.Println("Redis connected.")

	// 4. Initialize Scheduler and Worker
	ctx := context.Background()
	appScheduler := scheduler.NewScheduler(ctx, gormDB, redisClient)
	appWorker := worker.NewWorker(ctx, gormDB, redisClient, cfg.WorkerConcurrency, cfg.WorkerPollInterval)

	// 5. Start the background worker in a goroutine
	go appWorker.Start()

	// 6. Setup and Start the Gin HTTP Server
	router := router.SetupRouter(gormDB, appScheduler)
	log.Println("Starting server on :8080")
	if err := router.Run(":8080"); err != nil {
		log.Fatalf("Failed to run server: %v", err)
	}
}
