package main

import (
	"context"
	"encoding/json"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"

	_ "github.com/rizqitaufiqf/go-scheduler/docs" // docs is generated by Swag CLI
	"github.com/rizqitaufiqf/go-scheduler/dto"
	"github.com/rizqitaufiqf/go-scheduler/worker"

	"github.com/rizqitaufiqf/go-scheduler/config"
	"github.com/rizqitaufiqf/go-scheduler/database"
	"github.com/rizqitaufiqf/go-scheduler/handler"
	"github.com/rizqitaufiqf/go-scheduler/repository"
	"github.com/rizqitaufiqf/go-scheduler/router"
	"github.com/rizqitaufiqf/go-scheduler/service"
)

// @title Go Task Scheduler API
// @version 1.0
// @description An API for scheduling and managing product-related tasks.
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email support@swagger.io
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host      localhost:8080
// @BasePath  /api/v1
// @schemes http

func main() {
	// 1. Load Configuration
	cfg, err := config.LoadConfig()
	if err != nil {
		log.Fatalf("Could not load config: %v", err)
	}
	// Print config as formatted JSON for readability
	cfgJSON, _ := json.MarshalIndent(cfg, "", "  ")
	log.Printf("Loaded configuration:\n%s", string(cfgJSON))

	// Initialize database
	db, err := database.InitDB(cfg.Dsn)
	if err != nil {
		log.Fatalf("[Main] Failed to initialize database: %v", err)
	}
	log.Printf("[Main] Database connected")

	// Auto-migrate tables
	// if err := db.AutoMigrate(
	// 	&dto.TaskScheduler{},
	// 	&dto.TaskEntity{},
	// 	&dto.TaskAction{},
	// 	&dto.Notification{},
	// 	&dto.NotificationReadStatus{},
	// 	&dto.Session{},
	// ); err != nil {
	// 	log.Fatalf("[Main] Auto-migration failed: %v", err)
	// }
	// log.Printf("[Main] Database migration completed")

	// 3. Initialize Redis
	redisClient := database.InitRedis(cfg.RedisAddr)
	if _, err := redisClient.Ping(redisClient.Context()).Result(); err != nil {
		log.Fatalf("[Main] Could not connect to Redis: %v", err)
	}
	log.Println("[Main] Redis connected.")

	// Create context for graceful shutdown
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// Initialize services
	var notificationService *service.NotificationService
	var wsHub *service.WebSocketHub
	var notificationHandler *handler.NotificationHandler
	var websocketHandler *handler.WebSocketHandler

	var pubsubService *service.PubSubService

	// Initialize repositories
	notificationRepo := repository.NewNotificationRepository(db, redisClient, cfg)

	if cfg.NotificationEnabled {
		log.Printf("[Main] Notification system enabled")

		// Initialize WebSocket Hub
		wsHub = service.NewWebSocketHub(cfg)
		go wsHub.Run(ctx)
		log.Printf("[Main] WebSocket Hub started")

		// Initialize Pub/Sub
		pubsubService = service.NewPubSubService(redisClient, cfg)

		// Initialize Notification Service
		notificationService = service.NewNotificationService(
			notificationRepo,
			pubsubService,
			wsHub,
			cfg,
		)

		// Initialize handlers that depend on the notification service
		notificationHandler = handler.NewNotificationHandler(notificationService)
		websocketHandler = handler.NewWebSocketHandler(wsHub, cfg, notificationService)

		// Start Pub/Sub listener with a handler that matches the expected signature.
		// This closure captures the `ctx` from the main function's scope.
		go pubsubService.Listen(ctx, func(notification *dto.Notification) {
			notificationService.HandleNotification(ctx, notification)
		})
		log.Printf("[Main] Pub/Sub listener started on channel: %s", cfg.NotificationRedisChannel)

		// Start cleanup job
		go notificationService.StartCleanupJob(ctx)
		log.Printf("[Main] Notification cleanup job started")
	} else {
		log.Printf("[Main] Notification system disabled")
	}

	// Initialize worker
	w := worker.NewWorker(ctx, db, redisClient, cfg, notificationService)
	go w.Start()
	log.Printf("[Main] Worker started")

	// Initialize handlers
	productRepo := repository.NewProductRepository(db)
	productHandler := handler.NewProductHandler(productRepo)

	schedulerRepo := repository.NewScheduler(ctx, db, redisClient)
	taskHandler := handler.NewTaskHandler(db, schedulerRepo)
	authHandler := handler.NewAuthHandler(cfg)

	// Setup router
	r := router.SetupRouter(&router.RouterConfig{
		Cfg:                 cfg,
		RedisClient:         redisClient,
		Db:                  db,
		AuthHandler:         authHandler,
		NotificationHandler: notificationHandler,
		WebsocketHandler:    websocketHandler,
		ProductHandler:      productHandler,
		TaskHandler:         taskHandler,
	})

	// Start HTTP server in goroutine
	go func() {
		if err := r.Run(":8080"); err != nil && err.Error() != "http: Server closed" {
			log.Fatalf("[Main] Failed to start server: %v", err)
		}
	}()
	log.Printf("[Main] HTTP server started on :8080")

	// Wait for interrupt signal
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	log.Println("[Main] Shutting down gracefully...")
	cancel()
	time.Sleep(2 * time.Second)
	log.Println("[Main] Server stopped")
}
